# Generated by Django 3.2 on 2024-02-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Svetofor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, verbose_name='ip address')),
                ('local', models.CharField(max_length=30)),
                ('protocol', models.CharField(max_length=30)),
            ],
        ),
    ]
